export const SHORTEN_URL_REQUEST = "SHORTEN_URL_REQUEST"
export const SHORTEN_URL_SUCCESS = "SHORTEN_URL_SUCCESS"
export const SHORTEN_URL_FAILURE = "SHORTEN_URL_FAILURE"

export const EDIT_URL_REQUEST = "EDIT_URL_REQUEST"
export const EDIT_URL_SUCCESS = "EDIT_URL_SUCCESS"
export const EDIT_URL_FAILURE = "EDIT_URL_FAILURE"

export const FETCH_ALL_URLS_REQUEST = "FETCH_ALL_URLS_REQUEST"
export const FETCH_ALL_URLS_SUCCESS = "FETCH_ALL_URLS_SUCCESS"
export const FETCH_ALL_URLS_FAILURE = "FETCH_ALL_URLS_FAILURE"